runtime: nodejs
env: flex
env_variables:
  SQL_USER: root
  SQL_PASSWORD: SApper81*!
  SQL_DATABASE: locationdevicemanagerdb
  INSTANCE_CONNECTION_NAME: locationdevicemanager:europe-north1:locationdevicemanager
beta_settings:
  cloud_sql_instances: locationdevicemanager:europe-north1:locationdevicemanager